---
- name: APT Get/Install Minimal
  apt: "name={{ item }} state=present"
  with_items:
    - nodejs
    - nodejs-legacy
    - npm

- name: NPM Get/Install Packages
  npm: name={{ item }} global=yes
  with_items:
    - bower
    - grunt-cli
    - gulp
    - pm2