---
- name: APT Get/Install Minimal
  apt: "name={{ item }} state=present"
  with_items:
    - python-apt
    - python-pycurl

- name: APT Get/Install Packages
  apt: "name={{ item }} state=present"
  with_items:
    - colordiff
    - curl
    - dos2unix
    - gettext
    - git-core
    - graphviz
    - imagemagick
    - ngrep
    - sqlite
    - subversion
    - unzip
    - wget
    - zip

- name: APT Get/Install Language Packages
  apt: "name={{ item }} state=present"
  with_items:
    - language-pack-en
    - language-pack-pt

- name: Copy Locale
  copy:
    src: locale
    dest: /etc/default/locale
    owner: root
    group: root
    mode: 0644
    force: yes
  notify:
    - system locale | compile files
    - system locale | reconfigure

- name: Copy Timezone
  copy:
    src: timezone
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
    force: yes
  notify:
    - system timezone | reconfigure