---
- name: APT Get/Install Minimal
  apt: "name={{ item }} state=present"
  with_items:
    - php7.0
    - libapache2-mod-php7.0

- name: APT Get/Install Packages
  apt: "name={{ item }} state=present"
  with_items:
    - php7.0-cli
    - php7.0-common
    - php7.0-curl
    - php7.0-dev
    - php7.0-fpm
    - php7.0-gd
    - php7.0-mbstring
    - php7.0-mcrypt
    - php7.0-mysql
    - php7.0-opcache
    - php7.0-pgsql
    - php7.0-sqlite3
    - php7.0-xml
    - php7.0-xmlrpc
    - php7.0-zip